version: '3'

services:
  web1:
    image: php:8.2.28-apache
    container_name: web1
    volumes:
      - ./web1:/var/www/html:ro
    ports:
      - "8080:80"
    working_dir: /var/www/html
    command: ["/bin/sh", "-c", "[ -d /var/www/html/flag ] && cp -r /var/www/html/flag / && rm -rf /var/www/html/flag; apache2-foreground"]

  web2:
    build: ./web2   
    container_name: web2
    volumes:
      - ./web2:/var/www/html
    ports:
      - "8081:80"
    working_dir: /var/www/html
    depends_on:
      - mongo         

  web3:
    image: php:8.2.28-apache
    container_name: web3
    volumes:
      - ./web3:/var/www/html:ro
    ports:
      - "8082:80"
    working_dir: /var/www/html

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "54088:54088"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

